# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true

branches:
    only:
        - master
        
os:
  - linux


compiler:
  - gcc


env:
  global:
    - CMAKE_BUILD_TYPE=RELEASE
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"


before_install:
  
  - sudo apt-get install libboost-all-dev
  - sudo apt-get update -qq
  - sudo apt-get install libarmadillo-dev libopenblas-dev libblas-dev libarpack++2-dev liblapack-dev
  - sudo apt-get install libgfortran3 gfortran
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/libgfortran.so
  - sudo apt-get install r-base-dev
  - sudo apt-get update


r_packages:
  - Matrix
  - Rcpp
  - RcppArmadillo
  - BH
  - R6
  - data.table
  - utils
  - testthat
  - covr
  - knitr
  - rmarkdown
  - devtools
  - roxygen2

